### ISSUE TITLE
Component: About me Card (Right Column with Introduction)

### ISSUE THREAD

**Issue by MateuszNaKodach** [AdamWanczyk/BusinessCard#10]
**Subtasks**
- [x] Create new branch with accurate name. Read in link below about GitHub Flow.
- [x] Implement the design using HTML and CSS. Just the header and introduction content.
- [x] When complete -> create Pull Request from the branch to `main`.

**Design**
![Introduction](https://github.com/AdamWanczyk/BusinessCard/assets/18637116/c915e2ab-949d-41b3-bb74-6c3fc10e726f)

**Links**
- [ ] GitHub Flow:
https://medium.com/@yanminthwin/understanding-github-flow-and-git-flow-957bc6e12220
