### ISSUE TITLE
Component: Main view Cards

### ISSUE THREAD

**Issue by MateuszNaKodach** [AdamWanczyk/BusinessCard#8]
**Subtasks**
- [x] Create new branch `features/#8_main-view-cards` and do all the work on the branch
- [x] Implement the design using HTML and CSS
- [x] Figma (The Force) is your ally. Now watch the [scene from Star Wars](https://www.youtube.com/watch?v=YEuA5Y_Cc88) and then use it to read fonts, sizes, colors etc. 
- [x] When complete -> create Pull Request from the branch to `main` and wait for review from @MateuszNaKodach 

**Design**
![SiteComponents](https://github.com/AdamWanczyk/BusinessCard/assets/18637116/320bf214-c9f3-400d-9983-f4a77d20d708)
